version: '3.8'

services:
  studyscraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    environment:
      - RUST_LOG=info
    command: ["studyscraper-rs"]
